Supersite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,  document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .import views

app_name = 'main'

urlpatterns = [
	path('', views.index, name='index'),
	path('wrapper', views.wrapper, name='wrapper'),
	path('contact/', views.contact, name='contact'),
	path('about/', views.about, name='about'),
	path('portfolio/', views.portfolio, name='portfolio'),
	path('service/', views.service, name='service'),
	path('blog/', views.blog, name='blog'),
	path('blog_detail/', views.blog_detail, name='blog_detail'),


]

main/models.py
from django.db import models
from django.urls import reverse
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField

class Blog(models.Model):
	title = models.CharField('Maqola nomi',max_length=300)
	body = RichTextField()
	slug = models.SlugField('*',max_length=100, unique=True, db_index=True)
	author = models.CharField('Muallif', default='Admin',max_length=200,blank=True)
	date = models.DateField("Qo'shilgan vaqti", auto_now_add=True)
	image = models.ImageField('Maqola rasmi', upload_to='Maqolalar_rasmi/')

	class Meta:
		verbose_name = 'Maqola'
		verbose_name_plural = 'Maqolalar'

	def get_absalute_url(self):   
		return reverse('main:blogDetailPage',kwargs={'blog_slug':self.slug})

	def __str__(self):
		return f'{self.title}'
		

class Contact(models.Model):
	name = models.CharField("F,I,SH",max_length=250)
	email = models.EmailField('Elektron pochta',max_length=100)
	phone = models.CharField("Telfon raqami",max_length=20)
	types = models.CharField('Qaysi xizmat turi',max_length=150)
	message = models.TextField("Xabari")

	class Meta:
		verbose_name = "Aloqa"
		verbose_name_plural = "Aloqalar"
	def __str__ (self):
		return f'{self.name}'		
class Comment(models.Model):
	blog_page = models.ForeignKey(Blog, on_delete=models.CASCADE, null=True)
	name = models.CharField('Ismi', max_length=50)
	message = models.TextField('Xabar',)

	class  Meta:
		verbose_name = 'Muhokama'
		verbose_name_plural = 'Muhokamalar'

	def __str__(self):
		return f"{self.name}"

class Portfolio(models.Model):
	title = models.CharField('Portfolio nomi',max_length=300)
	slug = models.SlugField('*',max_length=100, unique=True, db_index=True)
	author = models.CharField('Muallif', default='Admin',max_length=200,blank=True)
	date = models.DateField("Qo'shilgan vaqti", auto_now_add=True)
	image = models.ImageField('Maqola rasmi', upload_to='Maqolalar_rasmi/')
	body = RichTextField()
	class Meta:
		verbose_name = 'Portfolio'
		verbose_name_plural = 'Portfoliolar'

	def get_absalute_url(self):   
		return reverse('main:portfolioDetailPage',kwargs={'portfolio_slug':self.slug})
	def __str__(self):
		return f"{self.title}"	

main/views.py
from django.core.paginator import Paginator
from django.shortcuts import render
from.models import*
from django.contrib import messages

# Create your views here.
def index(request):
	
	return render(request,'index.html')
def wrapper(request):
	blog = Blog.objects.all().order_by("-id")[:5]
	return render(request,'wrapper.html',{'blog':blog})	
def contact(request):
	if request.method == 'POST':
		name = request.POST['name']
		email = request.POST['email']
		phone = request.POST['phone']
		message = request.POST['message']
		Contact.objects.create(
			name=name,
			email=email,
			phone=phone,
			message=message,
			),
	return render(request,'contact.html')
def about(request):

	return render(request, 'about.html')		
def service(request):

	return render(request, 'service.html')	
def blog(request):
	blog = Blog.objects.all().order_by("-id")[:10]
	return render(request,'blog-grid.html',{'blog':blog})
def portfolio(request):
	portfolio = Portfolio.objects.all().order_by("-id")[:10]
	return render(request,'portfolio.html',{'portfolio':portfolio})

def blog_detail(request,blog_slug):
	blog_page = Blog.objects.get(slug=blog_slug)
	if request.method == "POST":
		name = request.POST['name']
		message = request.POST['message']
		comment = Comment.objects.create(
			name=name,
			message=message,)
		comment.blog_page = blog_page
		comment.save()
	return render(request,'blog-details.html',{'blog_page':blog_page})

templates/blog-details.html
{% extends 'wrapper.html' %}
{% load static %}
{% block content %}
    <div class="section breadcrumb-section overlay" data-bg-image="assets/images/breadcrumb/portfolio.jpg">
        <div class="container">
            <div class="row">
                <div class="col-12">

                    <!-- Breadcrumb wrapper Start -->
                    <div class="breadcrumb-wrapper">
                        <h1 class="title text-white" data-aos="fade-up" data-aos-duration="1100">Blog Details</h1>

                        <ul class="breadcrumb-menu" data-aos="fade-up" data-aos-duration="1500">
                            <li>
                                <a href="index.html">Home</a>
                            </li>
                            <li>
                                <span>Blog Details Fullwidth</span>
                            </li>
                        </ul>
                    </div>
                    <!-- Breadcrumb wrapper End -->

                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb Section End -->

    <!-- Blog Grid Section Start -->
    <div class="section section-margin">
        <div class="container">

            <div class="row">
                <div class="col-lg-8 m-auto p-lg-0">
                    <div class="blog-details-wrapper">
                        <div class="blog-details-image m-b-40" data-aos="fade-up" data-aos-duration="1100">
                            <img src="/static/images/blog/blog-large/blog-details.png" alt="Blog Details">
                        </div>
                        <div class="single-blog-meta m-b-20" data-aos="fade-up" data-aos-duration="1200">
                            <span>By <a href="#/">Jems Bond,</a> March 20, 2021 / <a href="#/">Business</a></span>
                        </div>
                        <h2 class="blog-details-title m-b-20" data-aos="fade-up" data-aos-duration="1300">Business Management Consultancy</h2>
                        <p class="text" data-aos="fade-up" data-aos-duration="1100">Voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur mag ni dolores eos qui ratione voluptatem sequi nesciun Neque porro quisq uam est, qui dolorem ipsum quia dolor sit amet, consectetur some of the main Problems some of the main need more imporvement to solve the business policy sed quia consequuntur mag ni dolores eos qui ratione volup tatem sequi nesciunt. Neque porro quisq uam est, qui dolorem ipsum quia dolor sit amet, consectetur some of the main Problems some of themain need more imporvement to solve the business policy qui dolorem simple </p>
                        <p class="text" data-aos="fade-up" data-aos-duration="1100">Voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur mag ni dolores eos qui ratione voluptatem sequi nesciun Neque porro quisq uam est, qui dolorem ipsum quia dolor sit amet, consectetur some of the main Problems some of the main need more imporvement to solve the business policy qui dolorem simple ipsum consectetur</p>                  

                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Blog Grid Section End -->

    <!-- Newsletter Section Start -->
    
    <!-- Newsletter Section End -->
{% endblock %}

templates/blog-grid.html
{% extends 'wrapper.html' %}
{% load static %}
{% block content %}
    <!-- Breadcrumb Section Start -->
    <div class="section breadcrumb-section overlay" data-bg-image="/static/images/about/nMCFS6Uy1Po.jpg">
        <div class="container">
            <div class="row">
                <div class="col-12">

                    <!-- Breadcrumb wrapper Start -->
                    <div class="breadcrumb-wrapper">
                        <h1 class="title text-white" data-aos="fade-up" data-aos-duration="1100">Latest Blog Post</h1>

                        <ul class="breadcrumb-menu" data-aos="fade-up" data-aos-duration="1500">
                            <li>
                                <a href="index.html">Home</a>
                            </li>
                            <li>
                                <span>Blog Grid</span>
                            </li>
                        </ul>
                    </div>
                    <!-- Breadcrumb wrapper End -->

                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb Section End -->

    <!-- Blog Grid Section Start -->
    <div class="section section-margin">
        <div class="container">
            <div class="row m-b-n30">

                        {% for blog in blog %}
                <div class="col-lg-4 col-sm-6 m-b-30" data-aos="fade-up" data-aos-duration="1100">
                    <!-- Single Blog Wrapper Start -->
                    <div class="single-blog-wrapper">
                        <div class="single-blog-thumb">
                            <a class="image" href="{{blog.blog_detail}}"><img src="{{blog.image.url}}" alt="Blog Image"></a>
                        </div>
                        <div class="single-blog-content bg-color-gray">
                            <div class="blog-meta">
                                <span>By {{blog.author}} {{blog.date}}/ </span>
                            </div>
                            <h4 class="title"><a href="blog-details.html">{{blog.title}}</a></h4>
                            <p>{{blog.body|truncatewords:15}}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
                 
             
            </div>

        
        </div>
    </div>
    
{% endblock %}

templates/contact.html
{% extends 'wrapper.html'%}
{% load static %}
{% block content %}
    <!-- Breadcrumb Section Start -->
    <div class="section breadcrumb-section overlay" data-bg-image="/static/images/about/comprendre-les-differents-types-de-reseaux-telecoms.jpg">
        <div class="container">
            <div class="row">
                <div class="col-12">

                    <!-- Breadcrumb wrapper Start -->
                    <div class="breadcrumb-wrapper">
                        <h1 class="title text-white" data-aos="fade-up" data-aos-duration="1100">Contact Us</h1>

                        <ul class="breadcrumb-menu" data-aos="fade-up" data-aos-duration="1500">
                            <li>
                                <a href="{% url 'main:index' %}">Home</a>
                            </li>
                            <li>
                                <span>Contact</span>
                            </li>
                        </ul>
                    </div>
                    <!-- Breadcrumb wrapper End -->

                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb Section End -->

    <!-- Contact Wrapper Start -->
    <div class="section section-margin">
        <div class="container">
            <div class="row align-items-center m-b-n40">
                <div class="col-lg-5 m-b-40">

                    <div class="contact-content">

                        <!-- Section Title Start -->
                        <div class="section-title">
                            <h2 class="title">You can Communicate with us...</h2>
                            <p>Voluptas sit aspernatur aut odit aut fugit, sed quia consequu ntur magni dolores eos qui ratione voluptatem sequi fee</p>
                        </div>
                        <!-- Section Title End -->

                        <!-- Single Contact Start -->
                        <div class="single-contact" data-aos="fade-up" data-aos-duration="1200">
                            <span class="title">Address</span>
                            <p>Your address goes here, 120 example <br> North City, Country.</p>
                        </div>
                        <!-- Single Contact End -->

                        <!-- Single Contact Start -->
                        <div class="single-contact" data-aos="fade-up" data-aos-duration="1400">
                            <span class="title">Phone</span>
                            <a href="tel:123-123-456-789">+99899 810-70-90</a>
                            <a href="tel:123-123-456-789">+99899 814-70-90</a>
                        </div>
                        <!-- Single Contact End -->

                        <!-- Single Contact Start -->
                        <div class="single-contact" data-aos="fade-up" data-aos-duration="1600">
                            <span class="title">Web</span>
                            <a href="mailto:info@example.com">supersite@example.com</a>
                            <a href="https://www.google.com/supersite.uz">www.supersite.uz</a>
                        </div>
                        <!-- Single Contact End -->

                    </div>

                </div>
                <div class="col-lg-7 m-b-40">

                    <!-- Contact Form Wrapper Start -->
                    <div class="contact-form-wrapper contact-form">
                        <!-- Section Title Start -->
                        <div class="section-title p-b-15">
                            <h4 class="title">Send us a Message</h4>
                            <span></span>
                        </div>
                        <!-- Section Title End -->
                        <form action=""method="POST">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-12">
                                    <div class="row">

                                        <div class="col-md-12" data-aos="fade-up" data-aos-duration="1400">
                                            <div class="input-area m-b-20">
                                                <input class="input-item" type="text" placeholder="Your Name *" name="name">
                                            </div>
                                        </div>

                                        <div class="col-md-12" data-aos="fade-up" data-aos-duration="1600">
                                            <div class="input-area m-b-20">
                                                <input class="input-item" type="email" placeholder="Phone Number *" name="email">
                                            </div>
                                        </div>

                                        <div class="col-12" data-aos="fade-up" data-aos-duration="1800">
                                            <div class="input-area m-b-20">
                                               <input class="input-item" type="phone" placeholder="Phone Number" name="phone">
                                     
                                            </div>
                                        </div>

                                        <div class="col-12" data-aos="fade-up" data-aos-duration="2000">
                                            <div class="input-area m-b-40">
                                                <textarea cols="30" rows="5" class="textarea-item" name="message" placeholder="Message"></textarea>
                                            </div>
                                        </div>

                                        <div class="col-12" data-aos="fade-up" data-aos-duration="2200">
                                            <button type="submit" id="submit" name="submit" class="btn btn-dark btn-hover-primary">Send Now</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                    <!-- Contact Form Wrapper End -->

                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/portfolio.html
{% extends 'wrapper.html' %}
{% load static %}
{% block content %}
    <!-- Breadcrumb Section Start -->
    <div class="section breadcrumb-section overlay" data-bg-image="/static/images/about/Fotolia_60183824_XL-1-scaled.jpg">
        <div class="container">
            <div class="row">
                <div class="col-12">

                    <!-- Breadcrumb wrapper Start -->
                    <div class="breadcrumb-wrapper">
                        <h1 class="title text-white" data-aos="fade-up" data-aos-duration="1100">Portfolio</h1>

                        <ul class="breadcrumb-menu" data-aos="fade-up" data-aos-duration="1500">
                            <li>
                                <a href="{% url 'main:index' %}">Home</a>
                            </li>
                            <li>
                                <span>Portfolio</span>
                            </li>
                        </ul>
                    </div>
                    <!-- Breadcrumb wrapper End -->

                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb Section End -->

    <!-- Portfolio Section Start -->
      <div class="section section-margin">
        <div class="container">
            <div class="row m-b-n30">

                        {% for portfolio in portfolio %}
                <div class="col-lg-4 col-sm-6 m-b-30" data-aos="fade-up" data-aos-duration="1100">
                    <!-- Single Blog Wrapper Start -->
                    <div class="single-blog-wrapper">
                        <div class="single-blog-thumb">
                            <a class="image" href=""><img src="{{portfolio.image.url}}" alt="Blog Image"></a>
                        </div>
                        <div class="single-blog-content bg-color-gray">
                            <div class="blog-meta">
                                <span>By {{portfolio.author}} {{portfolio.date}}/ </span>
                            </div>
                            <h4 class="title"><a href="{% url 'main:blog' %}">{{portfolio.title}}</a></h4>
                            <p>{{portfolio.body|truncatewords:15}}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
                 
             
            </div>

        
        </div>
    </div>
    <!-- Portfolio Section End -->
{% endblock %}

templates/service.html
{% extends 'wrapper.html' %}
{% load static %}
{% block content %}
    <div class="section breadcrumb-section overlay" data-bg-image="/static/images/about/6.-Rabota-IT-spetsialistov.jpeg">
        <div class="container">
            <div class="row">
                <div class="col-12">

                    <!-- Breadcrumb wrapper Start -->
                    <div class="breadcrumb-wrapper">
                        <h1 class="title text-white" data-aos="fade-up" data-aos-duration="1100">Provide best Services <br> for your Company</h1>

                        <ul class="breadcrumb-menu" data-aos="fade-up" data-aos-duration="1500">
                            <li>
                                <a href="index.html">Home</a>
                            </li>
                            <li>
                                <span>Service</span>
                            </li>
                        </ul>
                    </div>
                    <!-- Breadcrumb wrapper End -->

                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb Section End -->

    <!-- About Section Start -->
    <div class="section section-margin">
        <div class="container">
            <div class="row m-b-n30 align-items-center">
                <div class="col-lg-6 m-b-30" data-aos="fade-up" data-aos-duration="1100">
                    <div class="about-content mw-100">
                        <h2 class="title">Fast Service, Talented People <br> Secure Payment</h2>
                        <span></span>
                        <p>Voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur mag ni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisq uam est, qui dolorem ipsum quia dolor sit amet, consectetur some of the main Problems some of the main need more imporvement to solve the business policy</p>
                        <p>Voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur mag ni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisq uam est, qui dolorem ipsum quia dolor sit amet, consectetur some of the main Problems some of the main need more imporvement to solve the business policy</p>
                    </div>
                </div>
                <div class="col-lg-6 order-first order-lg-last m-b-30" data-aos="fade-up" data-aos-duration="1500">
                    <div class="about-image service-layer-image ms-auto">
                        <img class="about-image-1" src="/static/images/about/about-2.png" alt="About Image">
                        <img class="about-image-2" src="/static/images/about/about-3.png" alt="About Image">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- About Section End -->

    <!-- Service Section Start -->
      <div class="section section-margin-bottom">
        <div class="container">
            <div class="row">
                <div class="col-12" data-aos="fade-up" data-aos-duration="1100">
                    <div class="section-title text-center">
                        <h2 class="title">What We Do</h2>
                        <span class="d-flex justify-content-center"></span>
                        <p class="m-auto">Create web site,Mobile App, Graphic Design,Telegram bot,Promotion and others</p>
                    </div>
                </div>
            </div>
            <div class="row m-b-n40">
                <div class="col-lg-4 col-sm-6 m-b-40" data-aos="fade-up" data-aos-duration="1100">
                    <!-- Single Service Start -->
                    <div class="single-service">
                        <div class="service-icon">
                            <img style="height:60px; width:70px;" src="/static/images/icon/icons8-website-50.png" alt="Service Icon">
                        </div>
                        <h4 class="title">WebSite Development</h4>
                        <p>Landing Page, Corporate website, Internet shop, Platforms, Individual.</p>
                        <a href="{% url 'main:contact' %}" class="btn btn-dark btn-hover-primary m-t-20">Order Now</a>
                    </div>
                    <!-- Single Service End -->
                </div>
                <div class="col-lg-4 col-sm-6 m-b-40" data-aos="fade-up" data-aos-duration="1200">
                    <!-- Single Service Start -->
                    <div class="single-service">
                        <div class="service-icon">
                            <img style="height:60px; width:70px;" src="/static/images/icon/kisspng-responsive-web-design-zen-cart-e-commerce-5afbf9e8beafc9.4755864615264629527811.jpg" alt="Service Icon">
                        </div>
                        <h4 class="title">Mobile App</h4>
                        <p>Informational, IOS & Android catalog, Internet shop, Platforms, Individual.</p>
                        <a href="{% url 'main:contact' %}" class="btn btn-dark btn-hover-primary m-t-20">Order Now</a>
                    </div>
                    <!-- Single Service End -->
                </div>
                <div class="col-lg-4 col-sm-6 m-b-40" data-aos="fade-up" data-aos-duration="1300">
                    <!-- Single Service Start -->
                    <div class="single-service">
                        <div class="service-icon">
                            <img style="height:60px; width:70px;" src="/static/images/icon/icons8-marketing-64.png" alt="Service Icon">
                        </div>
                        <h4 class="title">Promotion</h4>
                        <p>SMM Start, SMM Basic, SMM Profi, SEO optimization top 10, Contextual advertising</p> <a href="{% url 'main:contact' %}" class="btn btn-dark btn-hover-primary m-t-20">Order Now</a>
                    </div>
                    <!-- Single Service End -->
                </div>
                <div class="col-lg-4 col-sm-6 m-b-40" data-aos="fade-up" data-aos-duration="1400">
                    <!-- Single Service Start -->
                    <div class="single-service">
                        <div class="service-icon">
                            <img style="height:60px; width:70px;" src="/static/images/icon/icons8-telegram-app-50.png" alt="Service Icon">
                        </div>
                        <h4 class="title">Telegram Bot</h4>
                        <p>Informational, For online sales, Chain restaurant.</p> <a href="{% url 'main:contact' %}" class="btn btn-dark btn-hover-primary m-t-20">Order Now</a>
                    </div>
                    <!-- Single Service End -->
                </div>
                <div class="col-lg-4 col-sm-6 m-b-40" data-aos="fade-up" data-aos-duration="1500">
                    <!-- Single Service Start -->
                    <div class="single-service">
                        <div class="service-icon">
                            <img style="height:60px; width:70px;" src="/static/images/icon/service-5.png" alt="Service Icon">
                        </div>
                        <h4 class="title">Branding & Identity</h4>
                        <p>Naming, Logo, Brandbook, Business, Plans, Business Presentations.</p>
                         <a href="{% url 'main:contact' %}" class="btn btn-dark btn-hover-primary m-t-20">Order Now</a>
                    </div>
                    <!-- Single Service End -->
                </div>
                <div class="col-lg-4 col-sm-6 m-b-40" data-aos="fade-up" data-aos-duration="1600">
                    <!-- Single Service Start -->
                    <div class="single-service">
                        <div class="service-icon">
                            <img style="height:60px; width:70px;" src="/static/images/icon/service-2.png" alt="Service Icon">
                        </div>
                        <h4 class="title">Production</h4>
                        <p>Photography, Filming, Animation video. <br> <br></p>
                         <a href="{% url 'main:contact' %}" class="btn btn-dark btn-hover-primary m-t-20">Order Now</a>
                    </div>
                    <!-- Single Service End -->
                </div>
            </div>
        </div>
    </div>

    <!-- Service Section End -->

    <!-- Testimonial Section Start -->
   
    </div>
    <!-- Testimonial Section End -->
{% endblock %}